version: '3.7' 

services:
  app: 
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    ports:
      - "3081:3081"
    container_name: nodejs-api
    links:
      - mongo-db
    command: npm run start
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db

