version: '3.7' 

services:
  app: 
    build: . 
    links:
      - mongo-db
    command: npm run start
    ports:
      - '3081:3081'
    volumes:
      - .:/usr/app

  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db

